export interface Job {
  id: string
  title: string
  customer: string
  startTime: string
  endTime: string
  status: "scheduled" | "in-progress" | "completed" | "cancelled"
  priority: "low" | "medium" | "high" | "urgent"
  location: string
  address: string
  lat: number
  lng: number
  description?: string
  estimatedDuration?: string
}

export interface Technician {
  id: string
  name: string
  role: string
  status: "available" | "on-job" | "on-break" | "offline"
  avatar?: string
  phone?: string
  email?: string
  jobs: Job[]
}

export const mockTechnicians: Technician[] = [
  {
    id: "1",
    name: "John Doe",
    role: "Senior Technician",
    status: "on-job",
    email: "john.doe@company.com",
    phone: "(555) 123-4567",
    jobs: [
      {
        id: "j1",
        title: "HVAC Maintenance",
        customer: "ABC Corp",
        startTime: "08:00",
        endTime: "10:30",
        status: "completed",
        priority: "medium",
        location: "123 Main St",
        address: "123 Main St, Downtown",
        lat: 40.7128,
        lng: -74.0060,
        description: "Annual HVAC system maintenance and inspection",
        estimatedDuration: "2.5 hours",
      },
      {
        id: "j2",
        title: "Emergency Repair",
        customer: "XYZ Inc",
        startTime: "11:00",
        endTime: "14:00",
        status: "in-progress",
        priority: "urgent",
        location: "456 Oak Ave",
        address: "456 Oak Ave, Business District",
        lat: 40.7580,
        lng: -73.9855,
        description: "Emergency AC unit repair - not cooling",
        estimatedDuration: "3 hours",
      },
      {
        id: "j3",
        title: "Installation",
        customer: "Tech Solutions",
        startTime: "15:00",
        endTime: "17:30",
        status: "scheduled",
        priority: "high",
        location: "789 Pine Rd",
        address: "789 Pine Rd, Tech Park",
        lat: 40.7489,
        lng: -73.9680,
        description: "New HVAC system installation",
        estimatedDuration: "2.5 hours",
      },
    ],
  },
  {
    id: "2",
    name: "Jane Smith",
    role: "Field Technician",
    status: "available",
    email: "jane.smith@company.com",
    phone: "(555) 234-5678",
    jobs: [
      {
        id: "j4",
        title: "System Inspection",
        customer: "Global Systems",
        startTime: "09:00",
        endTime: "11:00",
        status: "completed",
        priority: "low",
        location: "321 Elm St",
        address: "321 Elm St, Industrial Zone",
        lat: 40.7614,
        lng: -73.9776,
        description: "Routine system inspection",
        estimatedDuration: "2 hours",
      },
      {
        id: "j5",
        title: "Preventive Maintenance",
        customer: "Local Business",
        startTime: "13:00",
        endTime: "15:00",
        status: "scheduled",
        priority: "medium",
        location: "654 Maple Dr",
        address: "654 Maple Dr, Shopping Center",
        lat: 40.7282,
        lng: -74.0776,
        description: "Scheduled preventive maintenance",
        estimatedDuration: "2 hours",
      },
    ],
  },
  {
    id: "3",
    name: "Mike Johnson",
    role: "Senior Technician",
    status: "on-job",
    email: "mike.johnson@company.com",
    phone: "(555) 345-6789",
    jobs: [
      {
        id: "j6",
        title: "Equipment Replacement",
        customer: "Manufacturing Co",
        startTime: "07:30",
        endTime: "12:00",
        status: "in-progress",
        priority: "high",
        location: "987 Industrial Pkwy",
        address: "987 Industrial Pkwy, Factory District",
        lat: 40.6782,
        lng: -73.9442,
        description: "Replace old HVAC equipment",
        estimatedDuration: "4.5 hours",
      },
      {
        id: "j7",
        title: "Follow-up Service",
        customer: "Retail Store",
        startTime: "13:30",
        endTime: "15:30",
        status: "scheduled",
        priority: "low",
        location: "147 Commerce Blvd",
        address: "147 Commerce Blvd, Shopping Mall",
        lat: 40.6892,
        lng: -73.9512,
        description: "Follow-up maintenance check",
        estimatedDuration: "2 hours",
      },
    ],
  },
  {
    id: "4",
    name: "Sarah Williams",
    role: "Field Technician",
    status: "on-break",
    email: "sarah.williams@company.com",
    phone: "(555) 456-7890",
    jobs: [
      {
        id: "j8",
        title: "Diagnostic Service",
        customer: "Healthcare Facility",
        startTime: "08:00",
        endTime: "10:00",
        status: "completed",
        priority: "medium",
        location: "258 Medical Center Dr",
        address: "258 Medical Center Dr, Hospital",
        lat: 40.7891,
        lng: -73.9535,
        description: "Diagnostic service for HVAC issues",
        estimatedDuration: "2 hours",
      },
      {
        id: "j9",
        title: "Repair Work",
        customer: "Office Complex",
        startTime: "14:00",
        endTime: "16:00",
        status: "scheduled",
        priority: "medium",
        location: "369 Corporate Way",
        address: "369 Corporate Way, Office Park",
        lat: 40.7549,
        lng: -73.9840,
        description: "Repair HVAC system in office building",
        estimatedDuration: "2 hours",
      },
    ],
  },
  {
    id: "5",
    name: "David Brown",
    role: "Lead Technician",
    status: "available",
    email: "david.brown@company.com",
    phone: "(555) 567-8901",
    jobs: [
      {
        id: "j10",
        title: "Emergency Call",
        customer: "Restaurant Chain",
        startTime: "10:00",
        endTime: "12:30",
        status: "completed",
        priority: "urgent",
        location: "741 Restaurant Row",
        address: "741 Restaurant Row, Food District",
        lat: 40.7312,
        lng: -74.0025,
        description: "Emergency refrigeration system repair",
        estimatedDuration: "2.5 hours",
      },
    ],
  },
  {
    id: "6",
    name: "Emily Davis",
    role: "Field Technician",
    status: "on-job",
    email: "emily.davis@company.com",
    phone: "(555) 678-9012",
    jobs: [
      {
        id: "j11",
        title: "Annual Inspection",
        customer: "Office Building",
        startTime: "07:00",
        endTime: "09:00",
        status: "completed",
        priority: "low",
        location: "852 Business Park",
        address: "852 Business Park, Corporate Center",
        lat: 40.7423,
        lng: -73.9902,
        description: "Annual HVAC system inspection",
        estimatedDuration: "2 hours",
      },
      {
        id: "j12",
        title: "System Upgrade",
        customer: "Tech Startup",
        startTime: "10:00",
        endTime: "13:00",
        status: "in-progress",
        priority: "high",
        location: "963 Innovation Dr",
        address: "963 Innovation Dr, Tech Hub",
        lat: 40.7556,
        lng: -73.9778,
        description: "Upgrade to smart HVAC system",
        estimatedDuration: "3 hours",
      },
      {
        id: "j13",
        title: "Filter Replacement",
        customer: "School District",
        startTime: "14:30",
        endTime: "16:00",
        status: "scheduled",
        priority: "medium",
        location: "159 Education Way",
        address: "159 Education Way, School Campus",
        lat: 40.7634,
        lng: -73.9823,
        description: "Replace air filters in all units",
        estimatedDuration: "1.5 hours",
      },
    ],
  },
  {
    id: "7",
    name: "Robert Martinez",
    role: "Senior Technician",
    status: "on-job",
    email: "robert.martinez@company.com",
    phone: "(555) 789-0123",
    jobs: [
      {
        id: "j14",
        title: "Equipment Installation",
        customer: "Factory",
        startTime: "08:30",
        endTime: "11:30",
        status: "in-progress",
        priority: "high",
        location: "159 Industrial Ave",
        address: "159 Industrial Ave, Manufacturing District",
        lat: 40.6956,
        lng: -73.9389,
        description: "Install new industrial HVAC units",
        estimatedDuration: "3 hours",
      },
      {
        id: "j15",
        title: "Maintenance Check",
        customer: "Warehouse",
        startTime: "14:00",
        endTime: "16:30",
        status: "scheduled",
        priority: "medium",
        location: "357 Storage Rd",
        address: "357 Storage Rd, Logistics Center",
        lat: 40.6845,
        lng: -73.9456,
        description: "Quarterly maintenance inspection",
        estimatedDuration: "2.5 hours",
      },
    ],
  },
  {
    id: "8",
    name: "Lisa Anderson",
    role: "Field Technician",
    status: "available",
    email: "lisa.anderson@company.com",
    phone: "(555) 890-1234",
    jobs: [
      {
        id: "j16",
        title: "Consultation",
        customer: "New Client",
        startTime: "09:00",
        endTime: "10:00",
        status: "scheduled",
        priority: "low",
        location: "246 Prospect St",
        address: "246 Prospect St, Residential",
        lat: 40.7189,
        lng: -74.0145,
        description: "Initial consultation for new system",
        estimatedDuration: "1 hour",
      },
      {
        id: "j17",
        title: "Installation Project",
        customer: "Retail Chain",
        startTime: "11:00",
        endTime: "15:00",
        status: "scheduled",
        priority: "high",
        location: "468 Commerce Center",
        address: "468 Commerce Center, Mall",
        lat: 40.7267,
        lng: -74.0089,
        description: "Install HVAC in new retail location",
        estimatedDuration: "4 hours",
      },
    ],
  },
  {
    id: "9",
    name: "James Wilson",
    role: "Lead Technician",
    status: "on-job",
    email: "james.wilson@company.com",
    phone: "(555) 901-2345",
    jobs: [
      {
        id: "j18",
        title: "Emergency Service",
        customer: "Hospital",
        startTime: "07:00",
        endTime: "10:00",
        status: "completed",
        priority: "urgent",
        location: "579 Medical Plaza",
        address: "579 Medical Plaza, Healthcare District",
        lat: 40.7723,
        lng: -73.9601,
        description: "Critical HVAC system failure",
        estimatedDuration: "3 hours",
      },
      {
        id: "j19",
        title: "Follow-up Visit",
        customer: "Clinic",
        startTime: "11:30",
        endTime: "13:00",
        status: "in-progress",
        priority: "medium",
        location: "680 Health Center",
        address: "680 Health Center, Medical Building",
        lat: 40.7812,
        lng: -73.9689,
        description: "Post-repair system check",
        estimatedDuration: "1.5 hours",
      },
    ],
  },
  {
    id: "10",
    name: "Patricia Taylor",
    role: "Field Technician",
    status: "on-break",
    email: "patricia.taylor@company.com",
    phone: "(555) 012-3456",
    jobs: [
      {
        id: "j20",
        title: "Routine Maintenance",
        customer: "School District",
        startTime: "08:00",
        endTime: "11:00",
        status: "completed",
        priority: "medium",
        location: "791 Education Way",
        address: "791 Education Way, High School",
        lat: 40.7445,
        lng: -73.9934,
        description: "Routine maintenance on all units",
        estimatedDuration: "3 hours",
      },
      {
        id: "j21",
        title: "Duct Cleaning",
        customer: "Library",
        startTime: "15:00",
        endTime: "17:00",
        status: "scheduled",
        priority: "low",
        location: "234 Library Lane",
        address: "234 Library Lane, City Center",
        lat: 40.7534,
        lng: -73.9823,
        description: "Air duct cleaning service",
        estimatedDuration: "2 hours",
      },
    ],
  },
  {
    id: "11",
    name: "Christopher Moore",
    role: "Senior Technician",
    status: "on-job",
    email: "christopher.moore@company.com",
    phone: "(555) 123-4568",
    jobs: [
      {
        id: "j22",
        title: "System Repair",
        customer: "Data Center",
        startTime: "09:30",
        endTime: "14:00",
        status: "in-progress",
        priority: "urgent",
        location: "802 Server Farm Rd",
        address: "802 Server Farm Rd, Tech Complex",
        lat: 40.7667,
        lng: -73.9712,
        description: "Critical cooling system repair",
        estimatedDuration: "4.5 hours",
      },
      {
        id: "j23",
        title: "Testing",
        customer: "Data Center",
        startTime: "14:30",
        endTime: "16:00",
        status: "scheduled",
        priority: "high",
        location: "802 Server Farm Rd",
        address: "802 Server Farm Rd, Tech Complex",
        lat: 40.7667,
        lng: -73.9712,
        description: "System performance testing",
        estimatedDuration: "1.5 hours",
      },
    ],
  },
  {
    id: "12",
    name: "Jennifer Garcia",
    role: "Field Technician",
    status: "available",
    email: "jennifer.garcia@company.com",
    phone: "(555) 234-5679",
    jobs: [
      {
        id: "j24",
        title: "Initial Assessment",
        customer: "Shopping Mall",
        startTime: "10:00",
        endTime: "12:00",
        status: "scheduled",
        priority: "low",
        location: "913 Retail Plaza",
        address: "913 Retail Plaza, Shopping District",
        lat: 40.7378,
        lng: -74.0012,
        description: "Assessment for system upgrade",
        estimatedDuration: "2 hours",
      },
      {
        id: "j25",
        title: "Repair Work",
        customer: "Restaurant",
        startTime: "13:00",
        endTime: "15:00",
        status: "scheduled",
        priority: "medium",
        location: "024 Dining District",
        address: "024 Dining District, Food Avenue",
        lat: 40.7289,
        lng: -74.0067,
        description: "Kitchen ventilation repair",
        estimatedDuration: "2 hours",
      },
      {
        id: "j26",
        title: "Filter Service",
        customer: "Gym",
        startTime: "16:00",
        endTime: "17:00",
        status: "scheduled",
        priority: "low",
        location: "567 Fitness Blvd",
        address: "567 Fitness Blvd, Recreation Center",
        lat: 40.7201,
        lng: -74.0134,
        description: "Replace HVAC filters",
        estimatedDuration: "1 hour",
      },
    ],
  },
]
