/**
 * Purchase Orders Page - Server Component
 *
 * Performance optimizations:
 * - Server Component fetches data before rendering (no loading flash)
 * - Only interactive table/chart components are client-side
 * - Better SEO and initial page load performance
 */

import { notFound } from "next/navigation";
import { StatusPipeline } from "@/components/ui/status-pipeline";
import { type StatCard } from "@/components/ui/stats-cards";
import {
  type PurchaseOrder,
  PurchaseOrdersTable,
} from "@/components/work/purchase-orders-table";
import { PurchaseOrdersKanban } from "@/components/work/purchase-orders-kanban";
import { WorkDataView } from "@/components/work/work-data-view";
import { getActiveCompanyId } from "@/lib/auth/company-context";
import { createClient } from "@/lib/supabase/server";

function formatCurrency(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(cents / 100);
}

export default async function PurchaseOrdersPage() {
  const supabase = await createClient();

  if (!supabase) {
    return notFound();
  }

  // Get authenticated user
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return notFound();
  }

  // Get active company ID
  const activeCompanyId = await getActiveCompanyId();

  if (!activeCompanyId) {
    return notFound();
  }

  // Fetch purchase orders from database
  // Simplified query - removed foreign key joins that may cause issues
  const { data: purchaseOrdersRaw, error } = await supabase
    .from("purchase_orders")
    .select(
      `
      id,
      po_number,
      vendor,
      title,
      status,
      priority,
      total_amount,
      created_at,
      expected_delivery,
      auto_generated
    `
    )
    .eq("company_id", activeCompanyId)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching purchase orders:", error);
    console.error("Error details:", {
      message: error.message,
      code: error.code,
      details: error.details,
      hint: error.hint,
    });
    // Continue with empty array - page will show empty state
  }

  // Transform data for table component
  const purchaseOrders: PurchaseOrder[] = (purchaseOrdersRaw || []).map(
    (po: any) => ({
      id: po.id,
      poNumber: po.po_number,
      vendor: po.vendor || "Unknown Vendor",
      title: po.title,
      status: po.status,
      priority: po.priority,
      totalAmount: po.total_amount || 0,
      jobNumber: undefined, // Would need to join with jobs table
      requestedBy: "", // Would need to join with users table
      createdAt: po.created_at
        ? new Date(po.created_at).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          })
        : "",
      expectedDelivery: po.expected_delivery
        ? new Date(po.expected_delivery).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          })
        : undefined,
      autoGenerated: po.auto_generated || false,
    })
  );

  // Calculate stats from data
  const totalPOs = purchaseOrders.length;
  const pending = purchaseOrders.filter(
    (po) => po.status === "pending_approval"
  ).length;
  const ordered = purchaseOrders.filter((po) => po.status === "ordered").length;
  const received = purchaseOrders.filter((po) => po.status === "received")
    .length;
  const cancelled = purchaseOrders.filter((po) => po.status === "cancelled")
    .length;
  const totalValue = purchaseOrders.reduce(
    (sum, po) => sum + po.totalAmount,
    0
  );

  const purchaseOrderStats: StatCard[] = [
    {
      label: "Pending Approval",
      value: pending,
      change: pending > 0 ? 0 : 4.2,
      changeLabel: "awaiting approval",
    },
    {
      label: "Ordered",
      value: ordered,
      change: ordered > 0 ? 6.8 : 0,
      changeLabel: "in transit",
    },
    {
      label: "Received",
      value: received,
      change: received > 0 ? 8.5 : 0,
      changeLabel: "completed",
    },
    {
      label: "Total Value",
      value: formatCurrency(totalValue),
      change: totalValue > 0 ? 5.3 : 0,
      changeLabel: "across all orders",
    },
    {
      label: "Total Orders",
      value: totalPOs,
      change: totalPOs > 0 ? 7.1 : 0,
      changeLabel: "purchase orders",
    },
  ];

  return (
    <>
      <StatusPipeline compact stats={purchaseOrderStats} />
      <WorkDataView
        kanban={<PurchaseOrdersKanban orders={purchaseOrders} />}
        section="purchaseOrders"
        table={<PurchaseOrdersTable orders={purchaseOrders} itemsPerPage={50} />}
      />
    </>
  );
}
