/**
 * Purchase Orders Page - Server Component
 *
 * Performance optimizations:
 * - Server Component fetches data before rendering (no loading flash)
 * - Only interactive table/chart components are client-side
 * - Better SEO and initial page load performance
 */

import { notFound } from "next/navigation";
import { AppToolbar } from "@/components/layout/app-toolbar";
import { PurchaseOrderToolbarActions } from "@/components/work/purchase-order-toolbar-actions";
import {
  type PurchaseOrder,
  PurchaseOrdersTable,
} from "@/components/work/purchase-orders-table";
import { getActiveCompanyId } from "@/lib/auth/company-context";
import { createClient } from "@/lib/supabase/server";

function formatCurrency(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(cents / 100);
}

export default async function PurchaseOrdersPage() {
  const supabase = await createClient();

  if (!supabase) {
    return notFound();
  }

  // Get authenticated user
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return notFound();
  }

  // Get active company ID
  const activeCompanyId = await getActiveCompanyId();

  if (!activeCompanyId) {
    return notFound();
  }

  // Fetch purchase orders from database
  // Simplified query - removed foreign key joins that may cause issues
  const { data: purchaseOrdersRaw, error } = await supabase
    .from("purchase_orders")
    .select(
      `
      id,
      po_number,
      vendor,
      title,
      status,
      priority,
      total_amount,
      created_at,
      expected_delivery,
      auto_generated
    `
    )
    .eq("company_id", activeCompanyId)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching purchase orders:", error);
    console.error("Error details:", {
      message: error.message,
      code: error.code,
      details: error.details,
      hint: error.hint,
    });
    // Continue with empty array - page will show empty state
  }

  // Transform data for table component
  const purchaseOrders: PurchaseOrder[] = (purchaseOrdersRaw || []).map(
    (po: any) => ({
      id: po.id,
      poNumber: po.po_number,
      vendor: po.vendor || "Unknown Vendor",
      title: po.title,
      status: po.status,
      priority: po.priority,
      totalAmount: po.total_amount || 0,
      jobNumber: undefined, // Would need to join with jobs table
      requestedBy: "", // Would need to join with users table
      createdAt: po.created_at
        ? new Date(po.created_at).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          })
        : "",
      expectedDelivery: po.expected_delivery
        ? new Date(po.expected_delivery).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          })
        : undefined,
      autoGenerated: po.auto_generated || false,
    })
  );

  // Calculate stats from data
  const totalPOs = purchaseOrders.length;
  const pending = purchaseOrders.filter(
    (po) => po.status === "pending_approval"
  ).length;
  const ordered = purchaseOrders.filter((po) => po.status === "ordered").length;
  const received = purchaseOrders.filter((po) => po.status === "received")
    .length;
  const totalValue = purchaseOrders.reduce(
    (sum, po) => sum + po.totalAmount,
    0
  );

  return (
    <>
      <AppToolbar
        config={{
          show: true,
          title: "Purchase Orders",
          subtitle: `${totalPOs} orders • ${formatCurrency(totalValue)} total`,
          actions: <PurchaseOrderToolbarActions />,
        }}
      />

      <div className="flex-1 overflow-auto p-6">
        <PurchaseOrdersTable orders={purchaseOrders} itemsPerPage={50} />
      </div>
    </>
  );
}
