import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  AlertTriangle,
  BadgeCheck,
  Beaker,
  Bell,
  Bot,
  Boxes,
  Calendar,
  CalendarCheck,
  CalendarRange,
  Camera,
  CheckCircle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  Download,
  FileCheck,
  FileText,
  Filter,
  FolderOpen,
  Gauge,
  GitBranch,
  GraduationCap,
  Handshake,
  Image as ImageIcon,
  LayoutDashboard,
  Leaf,
  Library,
  LineChart,
  Link as LinkIcon,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Navigation,
  PackageCheck,
  PackageSearch,
  RefreshCw,
  Repeat,
  Repeat2,
  Rocket,
  RotateCw,
  Route,
  Scale,
  Scan,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Signature,
  Sparkles,
  Trophy,
  Users,
  Wallet,
  Workflow,
} from "lucide-react";

const ICON_MAP = {
  bot: Bot,
  "calendar-check": CalendarCheck,
  "calendar-range": CalendarRange,
  calendar: Calendar,
  "message-circle": MessageCircle,
  filter: Filter,
  clock: Clock,
  "clipboard-list": ClipboardList,
  bell: Bell,
  workflow: Workflow,
  megaphone: Megaphone,
  "line-chart": LineChart,
  "map-pin": MapPin,
  signature: Signature,
  "credit-card": CreditCard,
  "badge-check": BadgeCheck,
  navigation: Navigation,
  "alert-triangle": AlertTriangle,
  download: Download,
  camera: Camera,
  handshake: Handshake,
  route: Route,
  "refresh-cw": RefreshCw,
  "repeat-2": Repeat2,
  gauge: Gauge,
  boxes: Boxes,
  scan: Scan,
  users: Users,
  "shield-check": ShieldCheck,
  trophy: Trophy,
  "file-text": FileText,
  wallet: Wallet,
  mail: Mail,
  link: LinkIcon,
  scale: Scale,
  shield: Shield,
  image: ImageIcon,
  "check-circle": CheckCircle,
  "clipboard-check": ClipboardCheck,
  timeline: GitBranch,
  settings: Settings,
  "file-check": FileCheck,
  leaf: Leaf,
  flask: Beaker,
  "shopping-cart": ShoppingCart,
  "layout-dashboard": LayoutDashboard,
  "alarm-clock": AlarmClock,
  "folder-open": FolderOpen,
  repeat: Repeat,
  library: Library,
  "package-search": PackageSearch,
  "package-check": PackageCheck,
  "rotate-cw": RotateCw,
  sparkles: Sparkles,
  rocket: Rocket,
  "graduation-cap": GraduationCap,
} satisfies Record<string, LucideIcon>;

type IconKey = keyof typeof ICON_MAP;

export function getMarketingIcon(name: string): LucideIcon {
  const key = name.toLowerCase() as IconKey;
  return ICON_MAP[key] ?? Sparkles;
}
