import { notFound } from "next/navigation";
import { PurchaseOrdersKanban } from "@/components/work/purchase-orders-kanban";
import {
	type PurchaseOrder,
	PurchaseOrdersTable,
} from "@/components/work/purchase-orders-table";
import { WorkDataView } from "@/components/work/work-data-view";
import { getActiveCompanyId } from "@/lib/auth/company-context";
import {
	getPurchaseOrdersPageData,
	PURCHASE_ORDERS_PAGE_SIZE,
} from "@/lib/queries/purchase-orders";

export async function PurchaseOrdersData({
	searchParams,
}: {
	searchParams?: { page?: string };
}) {
	const activeCompanyId = await getActiveCompanyId();

	if (!activeCompanyId) {
		return notFound();
	}

	const currentPage = Number(searchParams?.page) || 1;
	const { purchaseOrders: purchaseOrdersRaw, totalCount } =
		await getPurchaseOrdersPageData(
			currentPage,
			PURCHASE_ORDERS_PAGE_SIZE,
			activeCompanyId,
		);

	const purchaseOrders: PurchaseOrder[] = (purchaseOrdersRaw || []).map(
		(po) => ({
			id: po.id,
			poNumber: po.po_number,
			vendor: po.vendor || "Unknown Vendor",
			title: po.title,
			status: po.status,
			priority: po.priority,
			totalAmount: po.total_amount || 0,
			jobNumber: undefined,
			requestedBy: "",
			createdAt: po.created_at
				? new Date(po.created_at).toLocaleDateString("en-US", {
						month: "short",
						day: "numeric",
						year: "numeric",
					})
				: "",
			expectedDelivery: po.expected_delivery
				? new Date(po.expected_delivery).toLocaleDateString("en-US", {
						month: "short",
						day: "numeric",
						year: "numeric",
					})
				: undefined,
			autoGenerated: po.auto_generated,
			archived_at: po.archived_at,
			deleted_at: null,
		}),
	);

	return (
		<WorkDataView
			kanban={<PurchaseOrdersKanban orders={purchaseOrders} />}
			section="purchaseOrders"
			table={
				<PurchaseOrdersTable
					currentPage={currentPage}
					itemsPerPage={PURCHASE_ORDERS_PAGE_SIZE}
					orders={purchaseOrders}
					totalCount={totalCount}
				/>
			}
		/>
	);
}
