import { notFound } from "next/navigation";
import { PurchaseOrdersKanban } from "@/components/work/purchase-orders-kanban";
import {
  type PurchaseOrder,
  PurchaseOrdersTable,
} from "@/components/work/purchase-orders-table";
import { WorkDataView } from "@/components/work/work-data-view";
import { getActiveCompanyId } from "@/lib/auth/company-context";
import { createClient } from "@/lib/supabase/server";

export async function PurchaseOrdersData() {
  const supabase = await createClient();

  if (!supabase) {
    return notFound();
  }

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return notFound();
  }

  const activeCompanyId = await getActiveCompanyId();

  if (!activeCompanyId) {
    return notFound();
  }

  const { data: purchaseOrdersRaw, error } = await supabase
    .from("purchase_orders")
    .select(
      `
      id,
      po_number,
      vendor,
      title,
      status,
      priority,
      total_amount,
      created_at,
      expected_delivery,
      auto_generated,
      archived_at
    `
    )
    .eq("company_id", activeCompanyId)
    .order("created_at", { ascending: false });

  if (error) {
    throw new Error(`Failed to fetch purchase orders: ${error.message}`);
  }

  // biome-ignore lint/suspicious/noExplicitAny: Supabase query result type
  const purchaseOrders: PurchaseOrder[] = (purchaseOrdersRaw || []).map(
    (po: any) => ({
      id: po.id,
      poNumber: po.po_number,
      vendor: po.vendor || "Unknown Vendor",
      title: po.title,
      status: po.status,
      priority: po.priority,
      totalAmount: po.total_amount || 0,
      jobNumber: undefined,
      requestedBy: "",
      createdAt: po.created_at
        ? new Date(po.created_at).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          })
        : "",
      expectedDelivery: po.expected_delivery
        ? new Date(po.expected_delivery).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          })
        : undefined,
      autoGenerated: po.auto_generated,
      archived_at: po.archived_at,
      deleted_at: null,
    })
  );

  return (
    <WorkDataView
      kanban={<PurchaseOrdersKanban orders={purchaseOrders} />}
      section="purchaseOrders"
      table={<PurchaseOrdersTable itemsPerPage={50} orders={purchaseOrders} />}
    />
  );
}
