"use client";

/**
 * Purchase Orders Data (Convex Version)
 *
 * Client component that fetches purchase order data from Convex.
 * Provides real-time updates via Convex subscriptions.
 *
 * Migration from: purchase-orders-data.tsx (Supabase Server Component)
 */
import { PurchaseOrdersKanban } from "@/components/work/purchase-orders-kanban";
import { type PurchaseOrder, PurchaseOrdersTable } from "@/components/work/purchase-orders-table";
import { WorkDataView } from "@/components/work/work-data-view";
import { usePurchaseOrders } from "@/lib/convex/hooks/purchase-orders";
import { useActiveCompany } from "@/lib/convex/hooks/use-active-company";
import { Skeleton } from "@/components/ui/skeleton";

const PURCHASE_ORDERS_PAGE_SIZE = 50;

/**
 * Format date for display
 */
function formatDate(timestamp?: number | null): string {
  if (!timestamp) return "";
  return new Date(timestamp).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

/**
 * Loading skeleton for purchase orders view
 */
function PurchaseOrdersLoadingSkeleton() {
  return (
    <div className="space-y-4 p-4">
      <div className="flex items-center justify-between">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-10 w-32" />
      </div>
      <div className="space-y-2">
        {Array.from({ length: 10 }).map((_, i) => (
          <Skeleton key={i} className="h-16 w-full" />
        ))}
      </div>
    </div>
  );
}

/**
 * Error state component
 */
function PurchaseOrdersError({ message }: { message: string }) {
  return (
    <div className="flex items-center justify-center p-8">
      <div className="text-center">
        <h3 className="text-lg font-semibold text-destructive">Error Loading Purchase Orders</h3>
        <p className="text-muted-foreground mt-2">{message}</p>
      </div>
    </div>
  );
}

/**
 * Empty state component
 */
function PurchaseOrdersEmpty() {
  return (
    <div className="flex items-center justify-center p-8">
      <div className="text-center">
        <h3 className="text-lg font-semibold">No Purchase Orders Yet</h3>
        <p className="text-muted-foreground mt-2">
          Create your first purchase order to get started.
        </p>
      </div>
    </div>
  );
}

/**
 * Props for PurchaseOrdersDataConvex
 */
interface PurchaseOrdersDataConvexProps {
  searchParams?: { page?: string };
}

/**
 * Purchase Orders Data - Client Component using Convex
 *
 * REAL-TIME UPDATES:
 * - Uses Convex subscriptions for live data updates
 * - No manual refresh needed
 * - Optimistic UI updates via mutations
 */
export function PurchaseOrdersDataConvex({ searchParams }: PurchaseOrdersDataConvexProps) {
  const currentPage = Number(searchParams?.page) || 1;
  const { activeCompanyId, isLoading: companyLoading } = useActiveCompany();

  // Fetch purchase orders from Convex
  const purchaseOrdersResult = usePurchaseOrders(
    activeCompanyId
      ? {
          companyId: activeCompanyId,
          limit: PURCHASE_ORDERS_PAGE_SIZE,
        }
      : "skip"
  );

  // Loading state
  if (companyLoading || purchaseOrdersResult === undefined) {
    return <PurchaseOrdersLoadingSkeleton />;
  }

  // No company selected
  if (!activeCompanyId) {
    return <PurchaseOrdersError message="Please select a company to view purchase orders." />;
  }

  // Error state
  if (purchaseOrdersResult === null) {
    return <PurchaseOrdersError message="Failed to load purchase orders. Please try again." />;
  }

  const { purchaseOrders: convexOrders, total, hasMore } = purchaseOrdersResult;

  // Empty state
  if (convexOrders.length === 0) {
    return <PurchaseOrdersEmpty />;
  }

  // Transform Convex records to table format
  const purchaseOrders: PurchaseOrder[] = convexOrders.map((po) => ({
    id: po._id,
    poNumber: po.poNumber,
    vendor: po.vendor || "Unknown Vendor",
    title: po.title,
    status: po.status,
    priority: po.priority,
    totalAmount: po.totalAmount || 0,
    jobNumber: undefined, // Job data not included in list query
    requestedBy: "", // User data not included in list query
    createdAt: formatDate(po._creationTime),
    expectedDelivery: formatDate(po.expectedDelivery),
    autoGenerated: po.autoGenerated,
    archived_at: po.archivedAt ? new Date(po.archivedAt).toISOString() : null,
    deleted_at: po.deletedAt ? new Date(po.deletedAt).toISOString() : null,
  }));

  return (
    <WorkDataView
      kanban={<PurchaseOrdersKanban orders={purchaseOrders} />}
      section="purchaseOrders"
      table={
        <PurchaseOrdersTable
          currentPage={currentPage}
          itemsPerPage={PURCHASE_ORDERS_PAGE_SIZE}
          orders={purchaseOrders}
          totalCount={total}
        />
      }
    />
  );
}

/**
 * Re-export original component for gradual migration
 */
export { PurchaseOrdersData } from "./purchase-orders-data";
