"use client";

import {
	Archive,
	CheckCircle2,
	Clock,
	Download,
	Loader2,
	MoreHorizontal,
	Package,
	PackageCheck,
	PackageX,
	Plus,
} from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import {
	bulkApprovePurchaseOrders,
	bulkArchivePurchaseOrders,
} from "@/actions/purchase-orders";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
	type BulkAction,
	type ColumnDef,
	FullWidthDataTable,
} from "@/components/ui/full-width-datatable";
import { formatCurrency } from "@/lib/formatters";
import { useArchiveStore } from "@/lib/stores/archive-store";

export type POStatus =
	| "draft"
	| "pending_approval"
	| "approved"
	| "ordered"
	| "partially_received"
	| "received"
	| "cancelled";

export type PurchaseOrder = {
	id: string;
	poNumber: string;
	vendor: string;
	title: string;
	status: POStatus;
	priority: "low" | "normal" | "high" | "urgent";
	totalAmount: number;
	jobNumber?: string;
	requestedBy: string;
	createdAt: string;
	expectedDelivery?: string;
	autoGenerated: boolean;
	archived_at?: string | null;
	deleted_at?: string | null;
};

const statusConfig: Record<
	POStatus,
	{ label: string; className: string; Icon: React.ElementType }
> = {
	draft: {
		label: "Draft",
		className:
			"bg-muted text-foreground dark:bg-foreground/20 dark:text-muted-foreground",
		Icon: Package,
	},
	pending_approval: {
		label: "Pending Approval",
		className: "bg-warning text-warning dark:bg-warning/20 dark:text-warning",
		Icon: Clock,
	},
	approved: {
		label: "Approved",
		className: "bg-success hover:bg-success text-white",
		Icon: CheckCircle2,
	},
	ordered: {
		label: "Ordered",
		className: "bg-primary text-primary dark:bg-primary/20 dark:text-primary",
		Icon: Package,
	},
	partially_received: {
		label: "Partially Received",
		className:
			"bg-accent text-accent-foreground dark:bg-accent/20 dark:text-accent-foreground",
		Icon: PackageCheck,
	},
	received: {
		label: "Received",
		className: "bg-success hover:bg-success text-white",
		Icon: PackageCheck,
	},
	cancelled: {
		label: "Cancelled",
		className:
			"bg-destructive text-destructive dark:bg-destructive/20 dark:text-destructive",
		Icon: PackageX,
	},
};

const priorityConfig: Record<
	"low" | "normal" | "high" | "urgent",
	{ label: string; className: string }
> = {
	low: { label: "Low", className: "text-primary" },
	normal: { label: "Normal", className: "text-muted-foreground" },
	high: { label: "High", className: "text-warning" },
	urgent: { label: "Urgent", className: "text-destructive" },
};

export function PurchaseOrdersTable({
	orders,
	itemsPerPage = 50,
	currentPage = 1,
	totalCount,
}: {
	orders: PurchaseOrder[];
	itemsPerPage?: number;
	currentPage?: number;
	totalCount?: number;
}) {
	const { toast } = useToast();
	const [isProcessing, setIsProcessing] = useState(false);
	const [selectedIds, setSelectedIds] = useState<string[]>([]);

	// Archive filter state
	const archiveFilter = useArchiveStore(
		(state) => state.filters.purchase_orders,
	);

	// Bulk action handlers
	const handleBulkApprove = async (ids: string[]) => {
		setIsProcessing(true);
		try {
			const result = await bulkApprovePurchaseOrders(ids);
			if (result.success) {
				toast.success(`${result.approvedCount} purchase orders approved`);
				setSelectedIds([]);
			} else {
				toast.error(result.error || "Failed to approve purchase orders");
			}
		} catch (_error) {
			toast.error("Failed to approve purchase orders");
		} finally {
			setIsProcessing(false);
		}
	};

	const handleBulkArchive = async (ids: string[]) => {
		setIsProcessing(true);
		try {
			const result = await bulkArchivePurchaseOrders(ids);
			if (result.success) {
				toast.success(`${result.archivedCount} purchase orders archived`);
				setSelectedIds([]);
			} else {
				toast.error(result.error || "Failed to archive purchase orders");
			}
		} catch (_error) {
			toast.error("Failed to archive purchase orders");
		} finally {
			setIsProcessing(false);
		}
	};

	const handleBulkExport = (ids: string[]) => {
		// Export selected items as CSV
		const selectedOrders = filteredOrders.filter((o) => ids.includes(o.id));
		const csv = [
			["PO Number", "Vendor", "Title", "Status", "Total Amount", "Expected Delivery"].join(","),
			...selectedOrders.map((po) =>
				[
					po.poNumber,
					`"${po.vendor.replace(/"/g, '""')}"`,
					`"${po.title.replace(/"/g, '""')}"`,
					po.status,
					po.totalAmount,
					po.expectedDelivery || "",
				].join(","),
			),
		].join("\n");

		const blob = new Blob([csv], { type: "text/csv" });
		const url = URL.createObjectURL(blob);
		const a = document.createElement("a");
		a.href = url;
		a.download = `purchase-orders-${new Date().toISOString().split("T")[0]}.csv`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
		toast.success(`Exported ${selectedOrders.length} purchase orders`);
	};

	// Filter orders based on archive status
	const filteredOrders = orders.filter((order) => {
		const isArchived = Boolean(order.archived_at || order.deleted_at);
		if (archiveFilter === "active") {
			return !isArchived;
		}
		if (archiveFilter === "archived") {
			return isArchived;
		}
		return true; // "all"
	});

	const columns: ColumnDef<PurchaseOrder>[] = [
		{
			key: "poNumber",
			header: "PO Number",
			width: "w-32",
			shrink: true,
			sortable: true,
			render: (po) => (
				<div className="flex items-center gap-2">
					<Link
						className="text-foreground hover:text-primary text-sm font-medium transition-colors hover:underline"
						href={`/dashboard/work/purchase-orders/${po.id}`}
						onClick={(e) => e.stopPropagation()}
					>
						{po.poNumber}
					</Link>
					{po.autoGenerated && (
						<Badge className="text-xs font-medium" variant="outline">
							Auto
						</Badge>
					)}
				</div>
			),
		},
		{
			key: "vendor",
			header: "Vendor",
			width: "w-36",
			shrink: true,
			sortable: true,
			hideable: false, // CRITICAL: Vendor essential for quick identification
			render: (po) => (
				<span className="text-foreground text-sm">{po.vendor}</span>
			),
		},
		{
			key: "title",
			header: "Title",
			width: "flex-1",
			sortable: true,
			render: (po) => (
				<Link
					className="block min-w-0"
					href={`/dashboard/work/purchase-orders/${po.id}`}
					onClick={(e) => e.stopPropagation()}
				>
					<div className="text-foreground truncate text-sm leading-tight font-medium hover:underline">
						{po.title}
					</div>
					{po.jobNumber && (
						<div className="text-muted-foreground mt-0.5 truncate text-xs leading-tight">
							Job: {po.jobNumber}
						</div>
					)}
				</Link>
			),
		},
		{
			key: "priority",
			header: "Priority",
			width: "w-24",
			shrink: true,
			hideOnMobile: true,
			sortable: true,
			hideable: true,
			render: (po) => (
				<span
					className={`text-sm font-medium ${priorityConfig[po.priority].className}`}
				>
					{priorityConfig[po.priority].label}
				</span>
			),
		},
		{
			key: "totalAmount",
			header: "Amount",
			width: "w-28",
			shrink: true,
			align: "right",
			sortable: true,
			hideable: false, // CRITICAL: Financial data essential
			render: (po) => (
				<span className="font-semibold tabular-nums">
					{formatCurrency(po.totalAmount)}
				</span>
			),
		},
		{
			key: "expectedDelivery",
			header: "Expected",
			width: "w-28",
			sortable: true,
			shrink: true,
			hideOnMobile: true,
			hideable: true,
			render: (po) => (
				<span className="text-muted-foreground text-sm tabular-nums">
					{po.expectedDelivery || "—"}
				</span>
			),
		},
		{
			key: "status",
			header: "Status",
			width: "w-40",
			shrink: true,
			sortable: true,
			hideable: false, // CRITICAL: Status key for action items
			render: (po) => {
				const config = statusConfig[po.status];
				return (
					<Badge
						className={`text-xs font-medium ${config?.className || ""}`}
						variant="outline"
					>
						{config?.label || po.status}
					</Badge>
				);
			},
		},
		{
			key: "actions",
			header: "",
			width: "w-10",
			shrink: true,
			render: (po) => (
				<div data-no-row-click>
					<DropdownMenu>
						<DropdownMenuTrigger asChild>
							<Button size="icon" variant="ghost">
								<MoreHorizontal className="size-4" />
							</Button>
						</DropdownMenuTrigger>
						<DropdownMenuContent align="end">
							<DropdownMenuLabel>Actions</DropdownMenuLabel>
							<DropdownMenuSeparator />
							{po.status === "pending_approval" && (
								<>
									<DropdownMenuItem>
										<CheckCircle2 className="mr-2 size-4" />
										Approve
									</DropdownMenuItem>
									<DropdownMenuItem className="text-destructive">
										<PackageX className="mr-2 size-4" />
										Reject
									</DropdownMenuItem>
									<DropdownMenuSeparator />
								</>
							)}
							{po.status === "approved" && (
								<>
									<DropdownMenuItem>
										<Package className="mr-2 size-4" />
										Mark as Ordered
									</DropdownMenuItem>
									<DropdownMenuSeparator />
								</>
							)}
							{(po.status === "ordered" ||
								po.status === "partially_received") && (
								<>
									<DropdownMenuItem>
										<PackageCheck className="mr-2 size-4" />
										Mark as Received
									</DropdownMenuItem>
									<DropdownMenuSeparator />
								</>
							)}
							<DropdownMenuItem>
								<Download className="mr-2 size-4" />
								Download PDF
							</DropdownMenuItem>
							<DropdownMenuSeparator />
							<DropdownMenuItem>
								<Archive className="mr-2 size-4" />
								Archive PO
							</DropdownMenuItem>
						</DropdownMenuContent>
					</DropdownMenu>
				</div>
			),
		},
	];

	const bulkActions: BulkAction[] = [
		{
			label: isProcessing ? "Processing..." : "Approve",
			icon: isProcessing ? (
				<Loader2 className="h-4 w-4 animate-spin" />
			) : (
				<CheckCircle2 className="h-4 w-4" />
			),
			onClick: handleBulkApprove,
			disabled: isProcessing,
		},
		{
			label: "Export",
			icon: <Download className="h-4 w-4" />,
			onClick: handleBulkExport,
		},
		{
			label: isProcessing ? "Processing..." : "Archive",
			icon: isProcessing ? (
				<Loader2 className="h-4 w-4 animate-spin" />
			) : (
				<Archive className="h-4 w-4" />
			),
			variant: "destructive",
			onClick: handleBulkArchive,
			disabled: isProcessing,
		},
	];

	const searchFilter = (po: PurchaseOrder, query: string) => {
		const searchStr = query.toLowerCase();
		return (
			po.poNumber.toLowerCase().includes(searchStr) ||
			po.vendor.toLowerCase().includes(searchStr) ||
			po.title.toLowerCase().includes(searchStr) ||
			po.jobNumber?.toLowerCase().includes(searchStr) ||
			po.status.toLowerCase().includes(searchStr)
		);
	};

	return (
		<FullWidthDataTable
			bulkActions={bulkActions}
			columns={columns}
			data={filteredOrders}
			emptyAction={
				<Button
					onClick={() =>
						(window.location.href = "/dashboard/work/purchase-orders/new")
					}
					size="sm"
				>
					<Plus className="mr-2 size-4" />
					Create Purchase Order
				</Button>
			}
			emptyIcon={
				<Package className="text-muted-foreground mx-auto h-12 w-12" />
			}
			emptyMessage="No purchase orders found"
			enableSelection={true}
			entity="purchase_orders"
			getHighlightClass={() => "bg-warning/30 dark:bg-warning/10"}
			getItemId={(po) => po.id}
			isArchived={(po) => Boolean(po.archived_at || po.deleted_at)}
			isHighlighted={(po) => po.status === "pending_approval"}
			itemsPerPage={itemsPerPage}
			currentPageFromServer={currentPage}
			serverPagination
			onRefresh={() => {
				window.location.reload();
			}}
			onRowClick={(po) => {
				window.location.href = `/dashboard/work/purchase-orders/${po.id}`;
			}}
			searchFilter={searchFilter}
			searchPlaceholder="Search by PO number, vendor, title, job, or status..."
			showArchived={archiveFilter !== "active"}
			showRefresh={false}
			totalCount={totalCount ?? filteredOrders.length}
		/>
	);
}
