#!/usr/bin/env python3
"""
Comprehensive Migration Consolidator
Reads all migration files and generates one comprehensive SQL setup script
"""

import re
from pathlib import Path
from collections import defaultdict
from typing import Set, List, Dict, Tuple

def extract_sql_blocks(content: str, pattern: str) -> List[str]:
    """Extract SQL blocks matching a pattern"""
    # Find all CREATE statements and extract full blocks
    blocks = []
    # Simple extraction - find CREATE statements
    matches = list(re.finditer(pattern, content, re.IGNORECASE | re.MULTILINE | re.DOTALL))
    for match in matches:
        # Extract from CREATE to semicolon
        start = match.start()
        # Find the end of the statement (semicolon)
        end = content.find(';', start)
        if end != -1:
            blocks.append(content[start:end+1])
    return blocks

def main():
    migrations_dir = Path("supabase/migrations")
    output_file = Path("supabase/setup_database_from_scratch.sql")
    
    print(f"Reading migrations from {migrations_dir}")
    print(f"Output file: {output_file}")
    
    # Collect all SQL components
    extensions = set()
    enums = {}  # enum_name -> definition
    tables = {}  # table_name -> definition
    functions = {}  # function_name -> definition
    indexes = []  # List of index statements
    triggers = []  # List of trigger statements
    policies = []  # List of policy statements
    views = []  # List of view statements
    
    # Read all migration files
    migration_files = sorted([f for f in migrations_dir.glob("*.sql") if not f.name.endswith('.bak')])
    print(f"Found {len(migration_files)} migration files")
    
    for sql_file in migration_files:
        print(f"  Processing: {sql_file.name}")
        content = sql_file.read_text()
        
        # Extract extensions
        ext_matches = re.findall(r'CREATE EXTENSION (?:IF NOT EXISTS )?["\']?([a-z-]+)', content, re.IGNORECASE)
        extensions.update(ext_matches)
        
        # Extract ENUMs
        enum_matches = re.findall(r'CREATE TYPE ([a-z_]+) AS ENUM', content, re.IGNORECASE)
        for enum_name in enum_matches:
            # Extract full CREATE TYPE statement
            enum_match = re.search(rf'CREATE TYPE {enum_name} AS ENUM[^;]+;', content, re.IGNORECASE | re.DOTALL)
            if enum_match and enum_name not in enums:
                enums[enum_name] = enum_match.group(0)
        
        # Extract CREATE TABLE statements
        table_matches = re.findall(r'CREATE TABLE (?:IF NOT EXISTS )?([a-z_]+)', content, re.IGNORECASE)
        for table_name in table_matches:
            if table_name not in tables:
                # Extract full CREATE TABLE statement
                # More complex - need to handle nested parentheses
                table_match = re.search(rf'CREATE TABLE (?:IF NOT EXISTS )?{table_name}[^;]+;', content, re.IGNORECASE | re.DOTALL)
                if table_match:
                    tables[table_name] = table_match.group(0)
    
    print(f"\nFound:")
    print(f"  Extensions: {len(extensions)}")
    print(f"  ENUMs: {len(enums)}")
    print(f"  Tables: {len(tables)}")
    
    print(f"\nWriting comprehensive SQL file...")
    # Write to output file (this is simplified - full implementation would be more complex)
    with open(output_file, 'w') as f:
        f.write("-- Auto-generated comprehensive database setup script\n")
        f.write("-- Generated by consolidate_migrations.py\n\n")
        f.write(f"-- Found {len(extensions)} extensions, {len(enums)} ENUMs, {len(tables)} tables\n\n")
    
    print(f"Done! Output written to {output_file}")

if __name__ == "__main__":
    main()


