#!/bin/bash

# List of unused files to delete
files=(
"apps/web/src/app/(dashboard)/dashboard/layout.tsx"
"apps/web/src/app/api/webrtc/call/route.ts"
"apps/web/src/app/api/webrtc/credential/route.ts"
"apps/web/src/app/layout.tsx"
"apps/web/src/components/work/payments-table.tsx"
"apps/web/src/lib/auth/session.ts"
"apps/web/src/lib/datatable/rowHighlight.ts"
"apps/web/src/lib/datatable/table-presets.ts"
"apps/web/src/lib/formatters.ts"
"apps/web/src/lib/telnyx/client.ts"
"eslint.config.mjs"
"packages/ui/src/components/ui/archive-confirm-dialog.tsx"
"packages/ui/src/components/ui/shadcn-io/kanban/index.tsx"
"packages/ui/src/lib/datatable/custom-column-renderer.tsx"
"scripts/debug-webhook.ts"
"scripts/setup-biezru-domain.ts"
"scripts/setup-inbound-email.ts"
"scripts/test-email-system.ts"
"scripts/test-resend-webhook.ts"
"scripts/test-webhook.ts"
"src/actions/email-actions.ts"
"src/actions/schedules.ts"
"src/components/ai-elements/canvas.tsx"
"src/components/ai-elements/chain-of-thought.tsx"
"src/components/ai-elements/checkpoint.tsx"
"src/components/ai-elements/code-block.tsx"
"src/components/ai-elements/confirmation.tsx"
"src/components/ai-elements/connection.tsx"
"src/components/ai-elements/context.tsx"
"src/components/ai-elements/controls.tsx"
"src/components/ai-elements/edge.tsx"
"src/components/ai-elements/image.tsx"
"src/components/ai-elements/inline-citation.tsx"
"src/components/ai-elements/node.tsx"
"src/components/ai-elements/open-in-chat.tsx"
"src/components/ai-elements/panel.tsx"
"src/components/ai-elements/plan.tsx"
"src/components/ai-elements/queue.tsx"
"src/components/ai-elements/reasoning.tsx"
"src/components/ai-elements/shimmer.tsx"
"src/components/ai-elements/sources.tsx"
"src/components/ai-elements/suggestion.tsx"
"src/components/ai-elements/task.tsx"
"src/components/ai-elements/tool.tsx"
"src/components/ai-elements/toolbar.tsx"
"src/components/ai-elements/web-preview.tsx"
"src/components/chat/icons.tsx"
"src/components/chat/multimodal-input.tsx"
"src/components/communication/[id]/[id]-data.tsx"
"src/components/communication/[id]/[id]-skeleton.tsx"
"src/components/communication/archive/archive-data.tsx"
"src/components/communication/archive/archive-skeleton.tsx"
"src/components/communication/communication-data.tsx"
"src/components/communication/communication-skeleton.tsx"
"src/components/communication/communication-verification-gate.tsx"
"src/components/communication/feed/feed-data.tsx"
"src/components/communication/feed/feed-skeleton.tsx"
"src/components/communication/general/general-data.tsx"
"src/components/communication/general/general-skeleton.tsx"
"src/components/communication/management/management-data.tsx"
"src/components/communication/management/management-skeleton.tsx"
"src/components/communication/messages/client/conversation/conversation-header.tsx"
"src/components/communication/messages/client/conversation/conversation-view.tsx"
"src/components/communication/messages/client/conversation/message-bubble.tsx"
"src/components/communication/messages/client/conversation/message-input-v2.tsx"
"src/components/communication/messages/client/keyboard-shortcuts-dialog.tsx"
"src/components/communication/messages/client/messages-layout.tsx"
"src/components/communication/messages/client/thread-list/thread-header.tsx"
"src/components/communication/messages/client/thread-list/thread-item.tsx"
"src/components/communication/messages/client/thread-list/thread-list.tsx"
"src/components/communication/messages/messages-data-v2.tsx"
"src/components/communication/messages/messages-page-client-v2.tsx"
"src/components/communication/messages/messages-skeleton.tsx"
"src/components/communication/sales/sales-data.tsx"
"src/components/communication/sales/sales-skeleton.tsx"
"src/components/communication/spam/spam-data.tsx"
"src/components/communication/spam/spam-skeleton.tsx"
"src/components/communication/starred/starred-data.tsx"
"src/components/communication/starred/starred-skeleton.tsx"
"src/components/communication/support/support-data.tsx"
"src/components/communication/support/support-skeleton.tsx"
"src/components/communication/technicians/technicians-data.tsx"
"src/components/communication/technicians/technicians-skeleton.tsx"
"src/components/communication/trash/trash-data.tsx"
"src/components/communication/trash/trash-skeleton.tsx"
"src/components/communication/unread/unread-data.tsx"
"src/components/communication/unread/unread-skeleton.tsx"
"src/components/layout/feature-roadmap.tsx"
"src/components/ui/carousel.tsx"
"src/components/work/job-details/job-appointments-table.tsx"
"src/components/work/job-details/job-enrichment-inline.tsx"
"src/components/work/job-details/lead-attribution-card.tsx"
"src/components/work/job-details/review-tracking-card.tsx"
"src/components/work/job-details/tags/add-tag-badge.tsx"
"src/components/work/job-details/team-member-selector.tsx"
"src/hooks/use-desktop-notifications.ts"
"src/hooks/use-keyboard-shortcuts.ts"
"src/lib/communications/sms.ts"
"src/lib/storage/upload.ts"
"src/lib/stores/message-input-store.ts"
"src/lib/stores/message-ui-store.ts"
"src/lib/stores/messages-store.ts"
"src/lib/stores/team-presence-store.ts"
)

echo "Starting to delete ${#files[@]} unused files..."

deleted_count=0
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "Deleted: $file"
        ((deleted_count++))
    else
        echo "File not found: $file"
    fi
done

echo "Deletion complete. Deleted $deleted_count out of ${#files[@]} files."
