"use client";

import {
	ArrowUpRight,
	CalendarDays,
	PackageCheck,
	Warehouse,
} from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { type ColumnMeta, EntityKanban } from "@/components/ui/entity-kanban";
import type { KanbanItemBase } from "@/components/ui/shadcn-io/kanban";
import type {
	POStatus,
	PurchaseOrder,
} from "@/components/work/purchase-orders-table";
import { cn } from "@/lib/utils";

type PurchaseOrderKanbanItem = KanbanItemBase & {
	order: PurchaseOrder;
};

const PO_COLUMNS: Array<{
	id: POStatus;
	name: string;
	accentColor: string;
}> = [
	{ id: "draft", name: "Draft", accentColor: "#6B7280" },
	{ id: "pending_approval", name: "Pending Approval", accentColor: "#F59E0B" },
	{ id: "approved", name: "Approved", accentColor: "#22C55E" },
	{ id: "ordered", name: "Ordered", accentColor: "#2563EB" },
	{
		id: "partially_received",
		name: "Partially Received",
		accentColor: "#9333EA",
	},
	{ id: "received", name: "Received", accentColor: "#16A34A" },
	{ id: "cancelled", name: "Cancelled", accentColor: "#EF4444" },
];

const columnLabel = new Map(
	PO_COLUMNS.map((column) => [column.id, column.name]),
);

const priorityBadge: Record<
	PurchaseOrder["priority"],
	{ label: string; className: string }
> = {
	low: { label: "Low", className: "bg-primary text-primary" },
	normal: { label: "Normal", className: "bg-muted text-muted-foreground" },
	high: { label: "High", className: "bg-warning text-warning" },
	urgent: { label: "Urgent", className: "bg-destructive text-destructive" },
};

const currencyFormatter = new Intl.NumberFormat("en-US", {
	style: "currency",
	currency: "USD",
});

export function PurchaseOrdersKanban({ orders }: { orders: PurchaseOrder[] }) {
	return (
		<EntityKanban<PurchaseOrder, POStatus>
			calculateColumnMeta={(columnId, items): ColumnMeta => {
				const columnItems = items.filter((item) => item.columnId === columnId);
				const total = columnItems.reduce(
					(sum, item) => sum + (item.entity as PurchaseOrder).totalAmount,
					0,
				);
				return { count: columnItems.length, total };
			}}
			columns={PO_COLUMNS}
			data={orders}
			entityName="POs"
			formatTotal={(total) => currencyFormatter.format(total / 100)}
			mapToKanbanItem={(order) => ({
				id: order.id,
				columnId: order.status,
				entity: order,
				order,
			})}
			renderCard={(item) => (
				<PurchaseOrderCard
					item={{ ...item, order: item.entity } as PurchaseOrderKanbanItem}
				/>
			)}
			renderDragOverlay={(item) => (
				<div className="w-[280px] rounded-xl border border-border/70 bg-background/95 p-4 shadow-lg">
					<PurchaseOrderCard
						item={{ ...item, order: item.entity } as PurchaseOrderKanbanItem}
					/>
				</div>
			)}
			showTotals={true}
			updateEntityStatus={(order, newStatus) => ({
				...order,
				status: newStatus,
			})}
		/>
	);
}

function PurchaseOrderCard({ item }: { item: PurchaseOrderKanbanItem }) {
	const { order, columnId } = item;
	const priority = priorityBadge[order.priority];

	return (
		<div className="space-y-3">
			<div className="flex items-start justify-between gap-3">
				<div>
					<p className="font-semibold text-muted-foreground text-xs uppercase tracking-wide">
						{order.poNumber}
					</p>
					<h3 className="font-semibold text-foreground text-sm">
						{order.title}
					</h3>
					<p className="text-muted-foreground text-xs">{order.vendor}</p>
					<div className="mt-2 flex flex-wrap items-center gap-2">
						<Badge
							className={cn(
								"text-xs",
								columnId === "cancelled" &&
									"bg-destructive/10 text-destructive",
								(columnId === "approved" || columnId === "received") &&
									"bg-primary/10 text-primary",
							)}
							variant={
								columnId === "cancelled"
									? "destructive"
									: columnId === "approved" || columnId === "received"
										? "secondary"
										: "outline"
							}
						>
							{columnLabel.get(columnId as POStatus) ?? columnId}
						</Badge>
						<Badge
							className={cn("text-xs", priority.className)}
							variant="outline"
						>
							{priority.label}
						</Badge>
						{order.autoGenerated && (
							<Badge
								className="bg-secondary/20 text-secondary-foreground/80"
								variant="secondary"
							>
								Auto-generated
							</Badge>
						)}
					</div>
				</div>
			</div>

			<div className="space-y-2 text-muted-foreground text-xs">
				<div className="flex items-center gap-2">
					<Warehouse className="size-4 text-primary" />
					<span className="font-medium text-foreground">
						{order.requestedBy}
					</span>
				</div>
				{order.jobNumber && (
					<div className="flex items-center gap-2">
						<PackageCheck className="size-4 text-primary" />
						<span>{order.jobNumber}</span>
					</div>
				)}
				<div className="flex items-center gap-2">
					<CalendarDays className="size-4 text-primary" />
					<span>
						{order.createdAt}
						{order.expectedDelivery && ` → ${order.expectedDelivery}`}
					</span>
				</div>
			</div>

			<div className="flex items-center justify-between pt-2 text-muted-foreground text-xs">
				<span>Total</span>
				<span className="font-semibold text-foreground">
					{currencyFormatter.format(order.totalAmount / 100)}
				</span>
			</div>

			<Button
				asChild
				className="w-full justify-between text-primary text-xs"
				size="sm"
				variant="ghost"
			>
				<Link href={`/dashboard/work/purchase-orders/${order.id}`}>
					View purchase order
					<ArrowUpRight className="size-3.5" />
				</Link>
			</Button>
		</div>
	);
}
